DROP DATABASE IF EXISTS jtt_adlister_db;

CREATE DATABASE jtt_adlister_db;

CREATE USER IF NOT EXISTS jtt_adlister_user@localhost IDENTIFIED BY 'codeup';

GRANT ALL PRIVILEGES ON jtt_adlister_db.* TO jtt_adlister_user@localhost;

USE jtt_adlister_db;

DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);




